Moved user and server commands to separated sections. Added a 'Main' section.

diff --git a/ddo b/ddo
--- a/ddo
+++ b/ddo
@@ -2151,8 +2151,12 @@ function radinit {
 }
 
 #------------------------------------------------------------------------------
-# SERVER COMMAND: ping
+# Server commands
 #------------------------------------------------------------------------------
+
+#---------------------
+# SERVER COMMAND: ping
+#---------------------
 
 function ping_preflight {
   return 0
@@ -2163,9 +2167,9 @@ function ping_command {
   return 0
 }
 
-#------------------------------------------------------------------------------
+#-----------------------------
 # SERVER COMMAND: apache2_init
-#------------------------------------------------------------------------------
+#-----------------------------
 
 apache2_init_DEPS="apache2ctl a2ensite a2dissite a2enmod a2dismod"
 package_Ubuntu_apache2ctl="apache2"
@@ -2206,9 +2210,9 @@ function apache2_init_command {
 }
 
 
-#------------------------------------------------------------------------------
+#---------------------------
 # SERVER COMMAND: init_vhost
-#------------------------------------------------------------------------------
+#---------------------------
 
 function init_vhost_preflight {
   preflight_sudo || return 1
@@ -2219,9 +2223,48 @@ function init_vhost_command {
   echo
 }
 
+#-----------------------------------
+# SERVER COMMAND: keyexchange_remote
+#-----------------------------------
+
+function keyexchange_remote_command {
+
+  # Parse the key.
+  local key="$1"
+  [ -z "$key" ] && fatal "No key given."
+
+  local type pubkey id
+  IFS=" " read type pubkey id <<< "${key}"
+  [ -z "$type" ] || [ -z "${pubkey}" ] || [ -z "${id}" ] && fatal "Bad key format."
+
+  # Append or write new key file.
+  local keyfile=~/.ssh/authorized_keys
+  if [ -f "${keyfile}" ]; then
+    if grep "${pubkey}" "${keyfile}" >> /dev/null; then
+      # Key already in authorized_keys.
+      echo "Key is already in file ${keyfile}, skipping."
+    else
+      # Append the file.
+      echo "${key}" >> "${keyfile}"
+      grep "${pubkey}" "${keyfile}" >> /dev/null ||
+        fatal "Could not append key to file ${keyfile}."
+      echo "Added key to ${keyfile}."
+    fi
+  else
+    # No existing file just write a new one.
+    echo "${key}" > "${keyfile}"
+    [ -f "${keyfile}" ] || fatal "Could not create file ${keyfile}."
+    echo "Created ${keyfile}."
+  fi
+}
+
 #------------------------------------------------------------------------------
+# User commands
+#------------------------------------------------------------------------------
+
+#-------------------
 # USER COMMAND: init
-#------------------------------------------------------------------------------
+#-------------------
 
 # Utility: Common initilization for the init[7|8]? commands.
 function init_init {
@@ -2252,9 +2295,9 @@ function init_command {
   init7 $@
 }
 
-#------------------------------------------------------------------------------
+#--------------------
 # USER COMMAND: init7
-#------------------------------------------------------------------------------
+#--------------------
 
 function init7_shorthelp {
   echo "Create a Drupal 7 installation."
@@ -2271,9 +2314,9 @@ function init7_command {
   sshcmd monkeysatkeyboards.com fletch init_vhost
 }
 
-#------------------------------------------------------------------------------
+#--------------------
 # USER COMMAND: init8
-#------------------------------------------------------------------------------
+#--------------------
 
 function init8_shorthelp {
   echo "Create a Drupal 8 installation."
@@ -2289,9 +2332,9 @@ function init8_command {
   echo "init8 ARGS: $@"
 }
 
-#------------------------------------------------------------------------------
+#----------------------
 # USER COMMAND: servers
-#------------------------------------------------------------------------------
+#----------------------
 
 function servers_shorthelp {
   echo "List available servers."
@@ -2305,9 +2348,9 @@ function servers_command {
   ls "$SCRIPTHOME/servers" | sed 's/.server//g'
 }
 
-#------------------------------------------------------------------------------
+#------------------------
 # USER COMMAND: addserver
-#------------------------------------------------------------------------------
+#------------------------
 
 read -d "" addserver_CONFIG <<EOF
 
@@ -2641,44 +2684,9 @@ EOF
 # TODO test apachectl access
 }
 
-#------------------------------------------------------------------------------
-# SERVER COMMAND: keyexchange_remote
-#------------------------------------------------------------------------------
-
-function keyexchange_remote_command {
-
-  # Parse the key.
-  local key="$1"
-  [ -z "$key" ] && fatal "No key given."
-
-  local type pubkey id
-  IFS=" " read type pubkey id <<< "${key}"
-  [ -z "$type" ] || [ -z "${pubkey}" ] || [ -z "${id}" ] && fatal "Bad key format."
-
-  # Append or write new key file.
-  local keyfile=~/.ssh/authorized_keys
-  if [ -f "${keyfile}" ]; then
-    if grep "${pubkey}" "${keyfile}" >> /dev/null; then
-      # Key already in authorized_keys.
-      echo "Key is already in file ${keyfile}, skipping."
-    else
-      # Append the file.
-      echo "${key}" >> "${keyfile}"
-      grep "${pubkey}" "${keyfile}" >> /dev/null ||
-        fatal "Could not append key to file ${keyfile}."
-      echo "Added key to ${keyfile}."
-    fi
-  else
-    # No existing file just write a new one.
-    echo "${key}" > "${keyfile}"
-    [ -f "${keyfile}" ] || fatal "Could not create file ${keyfile}."
-    echo "Created ${keyfile}."
-  fi
-}
-
-#------------------------------------------------------------------------------
+#--------------------------
 # USER COMMAND: keyexchange
-#------------------------------------------------------------------------------
+#--------------------------
 
 # TODO: keyexchange_addkey arg-command here that calls ssh-keygen, and remove
 # the ssh-keygen from addserver and use this instead.
@@ -2765,9 +2773,9 @@ function keyexchange_command {
   keyexchange "${keyexchange_keyfile}" "${keyexchange_server}"
 }
 
-#------------------------------------------------------------------------------
+#------------------------
 # USER COMMAND: modserver
-#------------------------------------------------------------------------------
+#------------------------
 
 function modserver_shorthelp {
   echo "Modify an existing server."
@@ -2781,9 +2789,9 @@ function modserver_command {
   echo "modserver ARGS: $@"
 }
 
-#------------------------------------------------------------------------------
+#------------------------
 # USER COMMAND: delserver
-#------------------------------------------------------------------------------
+#------------------------
 
 function delserver_shorthelp {
   echo "Remove a server."
@@ -2799,9 +2807,9 @@ function delserver_command {
   echo "delserver ARGS: $@"
 }
 
-#------------------------------------------------------------------------------
+#---------------------
 # USER COMMAND: update
-#------------------------------------------------------------------------------
+#---------------------
 
 function update_shorthelp {
   echo "Update Drupal project information from updates.drupal.org."
@@ -2835,9 +2843,9 @@ function update_command {
   echo "TODO update"
 }
 
-#------------------------------------------------------------------------------
+#-------------------
 # USER COMMAND: help
-#------------------------------------------------------------------------------
+#-------------------
 
 help_DEPS="tr fmt"
 package_Cygwin_tr="coreutils"
@@ -2893,6 +2901,7 @@ function package_Ubuntu {
 #------------------------------------------------------------------------------
 # Initialization.
 #------------------------------------------------------------------------------
+
 REMOTE=0
 declare -a PREFLIGHT_ERRORS
 declare -a PREFLIGHT_WARNINGS
@@ -3026,6 +3035,10 @@ echo "TESTVALUE" > "$TEMPDIR/writecheck"
 #    ynprompt v "Press 'y' to continue in UTF-8 mode or 'n' to change to ASCII." y || OUTPUT_MODE="ascii"
 #  fi
 #fi
+
+#------------------------------------------------------------------------------
+# Main
+#------------------------------------------------------------------------------
 
 # Preflght checks.
 for command_and_args in "${commands[@]}"; do
