Rearranged some freefloating utility functions and removed some dead code.

diff --git a/ddo b/ddo
--- a/ddo
+++ b/ddo
@@ -17,13 +17,6 @@ trap 'rm -rf "$TEMPDIR"' EXIT INT TERM HUP
 declare user
 [ -n "$USERNAME" ] && user="$USERNAME"
 [ -n "$USER" ] && user="$USER"
-REMOTE=0
-declare -a PREFLIGHT_ERRORS
-declare -a PREFLIGHT_WARNINGS
-flightcheck=0
-declare -a commands
-declare invalid_commands
-SED="sed" # needed because ns uses it, will be replaced in deps processing.
 
 #------------------------------------------------------------------------------
 # Utilities
@@ -61,13 +54,6 @@ SED="sed" # needed because ns uses it, will be replaced in deps processing.
 function get {
   var="$1"
   [ -n "${!var}" ] && echo "${!var}" || echo "$2"
-}
-
-function index {
-  var="$1"
-  deref="${!var}"
-  echo "var: ${deref[@]}"
-  [ -n "${!var[$2]}" ] && printf "${!var[$2]}" || printf "$3"
 }
 
 # ----------------------
@@ -150,15 +136,6 @@ function loadserver {
   n=$(ns $1 _options); export $n="${!n}"
   # TODO test required values and check alias against $1
   return 0
-}
-
-# TODO documentation.
-function makepipe {
-  local pipe="$TEMPDIR/$1"
-  mkfifo "${pipe}"
-  local rval=$?
-  printf "${pipe}"
-  return ${rval}
 }
 
 # -------------------------------------------------------
@@ -382,6 +359,72 @@ function func {
 #
 function ns {
   ${SED} "s/\s//g" <<< "$@"
+}
+
+# ------------------------
+# valid_command(command)
+# ------------------------
+#
+# Utility: Test if given command is NOT in the command list.
+#
+# ARGS:  - command: Command to test for.
+#
+# STDIN:   Unused
+#
+# STDOUT:  Unused
+#
+# VARS:    $COMMANDS: Input, global list of commands.
+#
+# RETURN:  0 if the command is valid, 1 otherwise (bash `if` compatible).
+#
+# USAGE EXAMPLES:
+#
+#   if ! valid_command $COMMAND; then
+#     usage "Unknown command \"$COMMAND\""; exit -2;
+#   fi
+#
+function valid_command {
+  [[ "$COMMANDS" =~ (^| )"$1"($| ) ]]
+  return $?
+}
+
+# -------------------------
+# valid_number(min, max, n)
+# -------------------------
+#
+# Utility: Check if a number is valid and in a given range.
+#
+# ARGS:  - min: Minimum value.
+#
+#        - max: Maximum value.
+#
+#        - n: String to test.
+#
+# STDIN:   Unused
+#
+# STDOUT:  Unused
+#
+# VARS:    None
+#
+# RETURN:  0 if the number is valid, 1 otherwise (bash `if` compatible).
+#
+function valid_number {
+  [ -n "$3" ] &&
+  [[ "$3" =~ ^[0-9]+$ ]] &&
+  [ $3 -ge $1 ] &&
+  [ $3 -lt $2 ] &&
+    return 0 ||
+    return 1
+}
+
+# TODO documentation.
+function trim {
+  sed 's/^[[:space:]]*//g; s/[[:space:]]*$//g;' <<< "$1"
+}
+
+# TODO documentation.
+function string_contains {
+  grep "$2" <<< "$1" >> /dev/null
 }
 
 # -------------
@@ -778,62 +821,6 @@ EOF
   longhelp "$command"
 }
 
-# ------------------------
-# valid_command(command)
-# ------------------------
-#
-# Utility: Test if given command is NOT in the command list.
-#
-# ARGS:  - command: Command to test for.
-#
-# STDIN:   Unused
-#
-# STDOUT:  Unused
-#
-# VARS:    $COMMANDS: Input, global list of commands.
-#
-# RETURN:  0 if the command is valid, 1 otherwise (bash `if` compatible).
-#
-# USAGE EXAMPLES:
-#
-#   if ! valid_command $COMMAND; then
-#     usage "Unknown command \"$COMMAND\""; exit -2;
-#   fi
-#
-function valid_command {
-  [[ "$COMMANDS" =~ (^| )"$1"($| ) ]]
-  return $?
-}
-
-# -------------------------
-# valid_number(min, max, n)
-# -------------------------
-#
-# Utility: Check if a number is valid and in a given range.
-#
-# ARGS:  - min: Minimum value.
-#
-#        - max: Maximum value.
-#
-#        - n: String to test.
-#
-# STDIN:   Unused
-#
-# STDOUT:  Unused
-#
-# VARS:    None
-#
-# RETURN:  0 if the number is valid, 1 otherwise (bash `if` compatible).
-#
-function valid_number {
-  [ -n "$3" ] &&
-  [[ "$3" =~ ^[0-9]+$ ]] &&
-  [ $3 -ge $1 ] &&
-  [ $3 -lt $2 ] &&
-    return 0 ||
-    return 1
-}
-
 #------------------------------------------------------------------------------
 # UI: basic prompts
 #------------------------------------------------------------------------------
@@ -956,6 +943,46 @@ function pwprompt {
       echo "Passwords do not match, please try again."
   done
   export $1="${prompt1}"
+}
+
+# TODO documentation.
+function serverprompt {
+  local f
+  local config=""
+  local -r serverprompt_field="$1"
+  local -a servers
+  for f in "$(ls "$SCRIPTHOME/servers/"*.server)"; do
+    local n="$(basename "${f}")"
+    local server="$(sed 's/\.server//g' <<< "${n}")"
+    loadserver "${server}"
+    local host="$(get $(ns "${server}" _host))"
+    config+="${server}|${server}: ${host}"$'\n'
+    servers[${#servers[@]}]="${server}"
+  done
+  # TODO if 0 servers, fatal; if 1 server, auto pick; else prompt.
+  if [ ${#servers[@]} = 0 ]; then
+    fatal "No servers are configured, please run $PROGRAM addserver."
+  elif [ ${#servers[@]} = 1 ]; then
+    echo
+    echo "Only one server is configured, selecting \"${servers[0]}\"."
+    export ${serverprompt_field}="${servers[0]}"
+  else
+    PROMPT="" radioprompt "${!serverprompt_field}" "$2" 3 <<< "${config}"
+    export ${serverprompt_field}="${selected_value}"
+  fi
+}
+
+# TODO documentation.
+function fileprompt {
+  # TODO don't exit unless [ -f $result ]
+  fileprompt_field="$1"
+  while : ; do
+    textprompt "$@"
+    export ${fileprompt_field}="$(trim "${!fileprompt_field}")"
+    [ -f "${!fileprompt_field}" ] && break
+    echo "Sorry I could not find or read file: ${!fileprompt_field}"
+    echo "Please try again."
+  done
 }
 
 # -------------------------------------------------------
@@ -2380,10 +2407,6 @@ read -d "" addserver_roles_CHECKBOXES <<EOF
   y  |  addserver_roles_production  |  Production server
 EOF
 
-function string_contains {
-  grep "$2" <<< "$1" >> /dev/null
-}
-
 function addserver_roles_sanitize {
   local roles=""
   string_contains "${addserver_roles}" "l" && roles+=l
@@ -2683,51 +2706,6 @@ read -d "" keyexchange_CONFIG << EOF
 
 EOF
 
-# TODO document and move to utils section.
-function trim {
-  sed 's/^[[:space:]]*//g; s/[[:space:]]*$//g;' <<< "$1"
-}
-
-# TODO document and move to UI section.
-function serverprompt {
-  local f
-  local config=""
-  local -r serverprompt_field="$1"
-  local -a servers
-  for f in "$(ls "$SCRIPTHOME/servers/"*.server)"; do
-    local n="$(basename "${f}")"
-    local server="$(sed 's/\.server//g' <<< "${n}")"
-    loadserver "${server}"
-    local host="$(get $(ns "${server}" _host))"
-    config+="${server}|${server}: ${host}"$'\n'
-    servers[${#servers[@]}]="${server}"
-  done
-  # TODO if 0 servers, fatal; if 1 server, auto pick; else prompt.
-  if [ ${#servers[@]} = 0 ]; then
-    fatal "No servers are configured, please run $PROGRAM addserver."
-  elif [ ${#servers[@]} = 1 ]; then
-    echo
-    echo "Only one server is configured, selecting \"${servers[0]}\"."
-    export ${serverprompt_field}="${servers[0]}"
-  else
-    PROMPT="" radioprompt "${!serverprompt_field}" "$2" 3 <<< "${config}"
-    export ${serverprompt_field}="${selected_value}"
-  fi
-}
-
-# TODO document and move to UI section.
-function fileprompt {
-  # TODO don't exit unless [ -f $result ]
-  fileprompt_field="$1"
-  while : ; do
-    textprompt "$@"
-    export ${fileprompt_field}="$(trim "${!fileprompt_field}")"
-    [ -f "${!fileprompt_field}" ] && break
-    echo "Sorry I could not find or read file: ${!fileprompt_field}"
-    echo "Please try again."
-  done
-}
-
 function keyexchange_shorthelp {
   echo "Exchange SSH keys with a server."
 }
@@ -2922,6 +2900,13 @@ function package_Ubuntu {
 #------------------------------------------------------------------------------
 # Initialization.
 #------------------------------------------------------------------------------
+REMOTE=0
+declare -a PREFLIGHT_ERRORS
+declare -a PREFLIGHT_WARNINGS
+flightcheck=0
+declare -a commands
+declare invalid_commands
+SED="sed" # needed because ns uses it, will be replaced in deps processing.
 
 prog LSB_RELEASE lsb_release && OS="$(${LSB_RELEASE} -si)" || OS="$(uname -o)"
 
